### ISSUE TITLE
Create guidance for building topic page

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos-code-sprint#47]
Something along the lines of:
1. Copy https://github.com/ioos/ioos-code-sprint/blob/gh-pages/_topics/2024-05-01-01-test_something.md?plain=1 to a new markdown file.
   1. The filename convention is as follows: 
       2024-05-01-`incrementor`-`title`.md
1. Adjust the filename to incrementor by 1 and adjust the text to something descriptive about the topic (`2024-05-01-01-test_something.md` -> `2024-05-01-02-ERDDAP_mobile_application.md`). Note, keep the date the same (`2024-05-01`) as this is used to build the pages.
1. Adjust the header content, indicating the incrementor in the filename (`number`), topic title (`title`), who will lead the topic (`pis`), the participants (`contributors`), and the GitHub issue (`github`). The coordinators will update the remaining fields in the header.
    ```
    ---
    number: 1
    title: Test something
    pis:
      - someone
    contributors:
      - someone
    github: ioos/ioos-code-sprint/issues/
    slack:
      - python
    breakout:
      - General Python
    year: 
      - 2024
    ---
    ``` 
1. Update the various sections of the webpage from the information in the GitHub issue. The formatting follows [markdown formatting](https://www.markdownguide.org/cheat-sheet/).
